server:
  port: 8080
spring:
  profiles:
    active: dev-postgres
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:pw44s-dev
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: dev-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/leplatdujour
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:pw44s-test
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop